# House Price Prediction Project

## Project Overview

This project builds an end-to-end machine learning system for predicting house prices.

The project covers:
- Data exploration and cleaning
- Exploratory Data Analysis (EDA)
- Feature engineering
- Regression model training and evaluation
- Model export
- FastAPI deployment
- React frontend integration

this is the over view

## 1. Import Libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 2. Load Dataset

In [3]:
df = pd.read_csv('C:\ML_Project\House_Price_Web_App\House_Price_Data\house_prices.csv')

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\lenovo\AppData\Local\Temp\ipykernel_26076\2400499114.py:1: SyntaxWarning: invalid escape sequence '\M'
  df = pd.read_csv('C:\ML_Project\House_Price_Web_App\House_Price_Data\house_prices.csv')

In [4]:
df.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN

## 4. Exploratory Data Analysis (EDA)

In [5]:
df.shape

(187531, 21)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              187531 non-null  int64
 1   Title              187531 non-null  object
 2   Description        184508 non-null  object
 3   Amount(in rupees)  187531 non-null  object
 4   Price (in rupees)  169866 non-null  float64
 5   location           187531 non-null  object
 6   Carpet Area        106858 non-null  object
 7   Status             186916 non-null  object
 8   Floor              180454 non-null  object
 9   Transaction        187448 non-null  object
 10  Furnishing         184634 non-null  object
 11  facing             117298 non-null  object
 12  overlooking        106095 non-null  object
 13  Society            77853 non-null   object
 14  Bathroom           186703 non-null  object
 15  Balcony            138596 non-null  object
 16  Car Parking        84174 non-null   object
 17  Ownership          122014 non-null  object
 18  Super Area         79846 non-null   object
 19  Dimensions         0 non-null       float64
 20  Plot Area          0 non-null       float64
dtypes: float64(3), int64(1), object(17)
memory usage: 30.0+ MB

In [7]:
df.describe()

               Index  Price (in rupees)  Dimensions  Plot Area
count  187531.000000       1.698660e+05         0.0        0.0
mean    93765.000000       7.583772e+03         NaN        NaN
std     54135.681003       2.724171e+04         NaN        NaN
min         0.000000       0.000000e+00         NaN        NaN
25%     46882.500000       4.297000e+03         NaN        NaN
50%     93765.000000       6.034000e+03         NaN        NaN
75%    140647.500000       9.450000e+03         NaN        NaN
max    187530.000000       6.700000e+06         NaN        NaN

In [10]:
df.describe(include='O')

,Title,Description,Amount(in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area
count,187531,184508,187531,187531,106858,186916,180454,187448,184634,117298,106095,77853,186703,138596,84174,122014,79846
unique,32446,65634,1561,81,2758,1,947,4,3,8,19,10376,11,11,229,4,2976
top,2 BHK Ready to Occupy Flat for sale in Divyasr...,Multistorey apartment is available for sale. I...,Call for Price,new-delhi,1000 sqft,Ready to Move,2 out of 4,Resale,Semi-Furnished,East,Main Road,Hamdam Apartment,2,2,1 Covered,Freehold,1100 sqft
freq,2106,2732,9684,27599,5285,186916,12433,144172,88318,54741,32193,1648,93007,51809,38754,112229,2599

## 3. Data Quality Inspection

Before cleaning the dataset, we will inspect missing values, duplicated rows, unique values, and invalid or suspicious values.

In [31]:
null_summary = pd.DataFrame({
    "Null count" : df.isna().sum(),
    "Null %" : (df.isna().mean() * 100).round(3)
    }).sort_values("Null %", ascending=False)

null_summary

                   Null count   Null %
Plot Area              187531  100.000
Dimensions             187531  100.000
Society                109678   58.485
Super Area             107685   57.423
Car Parking            103357   55.115
overlooking             81436   43.425
Carpet Area             80673   43.018
facing                  70233   37.451
Ownership               65517   34.937
Balcony                 48935   26.094
Price (in rupees)       17665    9.420
Floor                    7077    3.774
Description              3023    1.612
Furnishing               2897    1.545
Bathroom                  828    0.442
Status                    615    0.328
Transaction                83    0.044
Title                       0    0.000
location                    0    0.000
Amount(in rupees)           0    0.000
Index                       0    0.000

In [18]:
df.duplicated().sum()

0

In [21]:
df['Price (in rupees)'].describe()

count    1.698660e+05
mean     7.583772e+03
std      2.724171e+04
min      0.000000e+00
25%      4.297000e+03
50%      6.034000e+03
75%      9.450000e+03
max      6.700000e+06
Name: Price (in rupees), dtype: float64

In [25]:
(df['Price (in rupees)'] <= 0).sum()

11

## 4. Target Variable Identification

The dataset contains two price-related variables: the total property amount and the price per unit area.

I will investigate their definitions and relationship before selecting the target variable to avoid data leakage.

In [49]:
cols = ['Amount(in rupees)', 'Price (in rupees)', 'Carpet Area']
compare = df[cols].dropna().sample(10, random_state = 42)
compare

       Amount(in rupees)  Price (in rupees) Carpet Area
74615           1.40 Cr              6931.0   1700 sqft
35599            65 Lac              4062.0   1050 sqft
2013             75 Lac              6438.0    850 sqft
59753           1.63 Cr              8359.0   1300 sqft
183520           41 Lac              4328.0      68 sqm
186602         67.5 Lac              3886.0   1250 sqft
162497           47 Lac              4677.0   1005 sqft
157155          1.05 Cr              4667.0   1850 sqft
32680          86.3 Lac              7500.0   1000 sqft
141230          1.92 Cr             10667.0   1600 sqft

In [51]:
compare["Carpet Area (numeric)"] = compare["Carpet Area"].str.extract(r"([\d.]+)").astype(float)

compare["Price × Area"] = (
    compare["Price (in rupees)"] * compare["Carpet Area (numeric)"]
)

compare

,Amount(in rupees),Price (in rupees),Carpet Area,Carpet Area (numeric),Price × Area
74615,1.40 Cr,6931.0,1700 sqft,1700.0,11782700.0
35599,65 Lac,4062.0,1050 sqft,1050.0,4265100.0
2013,75 Lac,6438.0,850 sqft,850.0,5472300.0
59753,1.63 Cr,8359.0,1300 sqft,1300.0,10866700.0
183520,41 Lac,4328.0,68 sqm,68.0,294304.0
186602,67.5 Lac,3886.0,1250 sqft,1250.0,4857500.0
162497,47 Lac,4677.0,1005 sqft,1005.0,4700385.0
157155,1.05 Cr,4667.0,1850 sqft,1850.0,8633950.0
32680,86.3 Lac,7500.0,1000 sqft,1000.0,7500000.0
141230,1.92 Cr,10667.0,1600 sqft,1600.0,17067200.0

## 5. Target Variable

The target variable is `Amount(in rupees)`, which represents the total selling price of the property.

In [ ]:
print(df['Amount(in rupees)'].nunique())
print('-'*100)
df['Amount(in rupees)'].str.extract(r'([a-zA-Z]+)')

1561
----------------------------------------------------------------------------------------------------

0
Lac     112568
Cr       65279
Call      9684
Name: count, dtype: int64